# Pré-processamento

### Atos do agreement_knedle1_tac3.csv

In [1]:
import pandas as pd
import numpy as np
import nltk

df1 = pd.read_csv('agreement_knedle1_tac3.csv')
df1

,id_dodf,tipo_rel,id_rel,anotador_rel,tipo_ent,id_ent,anotador_ent,offset,length,texto
0,80_194.30.9.8,Ato_Reversao,R1,carlos_gabriel,nome,3537,carlos_gabriel,197948,23,YURI MACHADO DE MENEZES
1,80_194.30.9.8,Ato_Reversao,R1,carlos_gabriel,matricula,3538,carlos_gabriel,197983,8,61.836-5
2,80_194.30.9.8,Ato_Reversao,R1,carlos_gabriel,vigencia,3539,carlos_gabriel,198021,22,12 de setembro de 2008
3,80_194.30.9.8,Ato_Reversao,R1,carlos_gabriel,Ato_Reversao,3540,carlos_gabriel,197866,178,REVERTER o REGIME DE TEMPO INTEGRAL E DEDICACA...
4,87_118.20.6.8,Ato_Nomeacao_Comissionado,R1,lygia_paloma,nome,1583,lygia_paloma,212316,28,JOAO PAULO PATROCINA MARQUES
...,...,...,...,...,...,...,...,...,...,...
20750,13_212.10.10.2013,Ato_Substituicao,R40,khalil_carsten,matricula_substituido,8685,vinicius_borges,644324,9,174.833-5
20751,13_212.10.10.2013,Ato_Substituicao,R40,khalil_carsten,data_inicial,8686,vinicius_borges,644348,2,09
20752,13_212.10.10.2013,Ato_Substituicao,R40,khalil_carsten,data_final,8687,vinicius_borges,644353,10,11/10/2013
20753,13_212.10.10.2013,Ato_Substituicao,R40,khalil_carsten,motivo,8688,vinicius_borges,644380,32,ferias regulamentares da titular
20754,13_212.10.10.2013,Ato_Substituicao,R40,khalil_carsten,nome_substituto,112344,khalil_carsten,644086,42,VANESSA CARNEIRO FERNANDES FERREIRA AMARAL

In [2]:
df1['id_dodf'].value_counts()

20_147.21.7.2014     3020
12_244.21.11.2013    2551
13_212.10.10.2013    2069
6_191.13.9.2013      1504
10_193.17.9.2013     1379
9_202.27.9.2013      1205
18_119.12.6.2013     1086
19_152.28.7.2014     1042
17_133.28.6.2013      927
7_188.10.9.2013       920
5_56.19.3.2013        892
83_216.30.10.8        802
4_2.3.1.2013          721
16_167.14.8.2013      589
8_200.26.9.2013       480
15_166.13.8.2013      424
11_243.20.11.2013     355
14_204.1.10.2013      328
84_208.17.10.8        186
86_161.18.8.8         100
88_123.27.6.8          66
85_151.5.8.8           43
75_8.11.1.2008         24
77_185.17.9.8          12
78_173.1.9.8           11
82_88.12.5.8            8
87_118.20.6.8           6
80_194.30.9.8           4
81_231.20.11.8          1
Name: id_dodf, dtype: int64

In [3]:
atos = df1['tipo_rel'].value_counts().index

In [4]:
df1 = df1.filter(['tipo_ent', 'texto'], axis = 1)

In [5]:
df1 = df1.loc[df1['tipo_ent'].isin(atos)]
df1.columns = ['tipo_ato', 'ato']
df1 = df1.reset_index(drop = True)
df1

,tipo_ato,ato
0,Ato_Reversao,REVERTER o REGIME DE TEMPO INTEGRAL E DEDICACA...
1,Ato_Nomeacao_Comissionado,NOMEAR JOAO PAULO PATROCINA MARQUES para exerc...
2,Ato_Exoneracao_Comissionado,EXONERAR SEBASTIAO FRANCISCO DE QUEIROZ do Car...
3,Ato_Exoneracao_Comissionado,EXONERAR SEBASTIAO FRANCISCO DE QUEIROZ do Car...
4,Ato_Exoneracao_Comissionado,EXONERAR SEBASTIAO FRANCISCO DE QUEIROZ do Car...
...,...,...
2257,Ato_Retificacao_Efetivo,"Na Ordem de Servico de 24/07/2013, publicada n..."
2258,Ato_Retificacao_Efetivo,"Na Ordem de Servico de 02/04/2012, publicada n..."
2259,Ato_Retificacao_Efetivo,"Na Ordem de Servico de 24/07/2013, publicada n..."
2260,Ato_Retificacao_Efetivo,RETIFICAR na Portaria de 1o de outubro de 2013...
2261,Ato_Substituicao,DESIGNAR: VANESSA CARNEIRO FERNANDES FERREIRA ...

In [6]:
df1['tipo_ato'].value_counts()

Ato_Nomeacao_Comissionado         743
Ato_Exoneracao_Comissionado       501
Ato_Tornado_Sem_Efeito_Exo_Nom    272
Ato_Retificacao_Comissionado      224
Ato_Retificacao_Efetivo           173
Ato_Substituicao                  139
Ato_Exoneracao_Efetivo            120
Ato_Cessao                         30
Ato_Reversao                       21
Ato_Tornado_Sem_Efeito_Apo         15
Ato_Abono_Permanencia              14
Ato_Nomeacao_Efetivo               10
Name: tipo_ato, dtype: int64

### Atos do atos_segs.csv

In [7]:
df2 = pd.read_csv('atos_segs.csv')
df2

                   tipo_ato                                                ato
0                  nomeacao  NOMEAR LETÍCIA MATOS MAGALHÃES para exercer o ...
1                exoneracao  EXONERAR, a pedido, ANNA LUIZA BARCIA HALLEY d...
2                  nomeacao  NOMEAR SANDRA TURCATO JORGE TOLENTINO para exe...
3                  nomeacao  NOMEAR RAIMUNDO DA COSTA SANTOS NETO, Procurad...
4    ato_tornado_sem_efeito  TORNAR SEM EFEITO no Decreto de 02 de julho de...
..                      ...                                                ...
268            substituicao  DESIGNAR\nrespectivamente TEREZA CRISTINA DE A...
269            substituicao  Designar FLÁVIO DE ARAÚJO ALMEIDA, matrícula n...
270            substituicao  DESIGNAR OTAMÁ DANTAS BARRETO, matrícula\n159....
271             retificacao  RETIFICAR o Sexto Termo\nAditivo ao Contrato, ...
272             retificacao  RETIFICAR o Primeiro Termo Aditivo (45138948)\...

[273 rows x 2 columns]

In [8]:
df2['tipo_ato'].value_counts()

aposentadoria             69
nomeacao                  53
exoneracao                49
retificacao               38
substituicao              37
ato_tornado_sem_efeito    16
cessao                     9
reversao                   1
abono_de_permanência       1
Name: tipo_ato, dtype: int64

In [9]:
df2_nom = df2[df2.tipo_ato == 'nomeacao']
df2_exo = df2[df2.tipo_ato == 'exoneracao']

In [10]:
for ato in df2_nom.iterrows():
    if 'Comissão' not in ato[1][1] and 'Natureza Especial' not in ato[1][1] and 'Natureza\nEspecial' not in ato[1][1]:
        print("Índice = %d" %ato[0])
        print(ato[1][1], end = '\n\n')

Índice = 65
NOMEAR os candidatos abaixo, aprovados no concurso público a que se refere Edital
Normativo nº 08, de 02 de março de 2018, publicado no DODF nº 43, de 05 de março de
2018 e homologado pelo Edital de Resultado Final nº 46, de 26 de julho de 2018,
publicado no DODF nº 142, de 27 de julho de 2018, para exercerem o cargo de
ENFERMEIRO, da Carreira de Assistência à Saúde, do Quadro de Pessoal da Secretaria
de Estado de Saúde do Distrito Federal, em substituição às vacâncias ocorridas até o dia
23/07/2020, com base na instrução dos autos do processo SEI 00060-00304234/2020-61,
conforme a seguir: (especialidade, nome e classificação)
ENFERMEIRO FAMÍLIA E COMUNIDADE: TATIANA LIMA SANTOS, 105º

In [11]:
df2.loc[65]['tipo_ato'] = 'Ato_Nomeacao_Efetivo'

In [12]:
for ato in df2_exo.iterrows():
    if 'Comissão' not in ato[1][1] and 'Natureza Especial' not in ato[1][1] and 'Natureza\nEspecial' not in ato[1][1]:
        print("Índice = %d" %ato[0])
        print(ato[1][1], end = '\n\n')

Índice = 79
EXONERAR, a pedido, MARCOS PAULO THOME ,
matrícula 1694552-2, Analista de Atividades do Hemocentro, especialidade Analista de
Laboratório, a contar de 03/08/202 , nos termos do artigo 51 da Lei Complementar
840/2011, conforme processo SEI nº 00063-00003412/2020-55.

Índice = 201
EXONERAR, a pedido, RUBENS
DE AZEVEDO RAMOS, da Carreira de ASSISTÊNCIA PÚBLICA À SAÚDE, cargo de
TÉCNICO EM SAÚDE - TECNICO EM NUTRICAO, I2-13, Matrícula nº. 0122800-5,
do Quadro de Pessoal do Distrito Federal com lotação na Secretaria de Estado de Saúde
do Distrito Federal, com base nos termos do caput do Artigo 51, da Lei Complementar nº.
840/2011, lotado(a) no(a) ADMINISTRAÇÃO CENTRAL (DRH/RES - DEPART. DE
REC. HUMANOS), declarando vago o referido cargo, a contar de 24 de setembro de
1992, nos termos do artigo 50, Inciso I, da supramencionada Lei, conforme Processo nº
00060-00087027/2020-37.

In [13]:
df2.loc[79]['tipo_ato'] = 'Ato_Exoneracao_Efetivo'
df2.loc[201]['tipo_ato'] = 'Ato_Exoneracao_Efetivo'

In [14]:
df2 = df2[df2.tipo_ato != 'retificacao']
df2 = df2[df2.tipo_ato != 'ato_tornado_sem_efeito']

### Atos de 2020 anotados

In [15]:
df3 = pd.read_csv('atos_2020_anotados2.csv', index_col = 0)
df3

             tipo_ato                                                ato
0   Ato_Aposentadoria  CONCEDER APOSENTADORIA, nos termos do artigo 3...
1   Ato_Aposentadoria  CONCEDER APOSENTADORIA, nos termos do artigo 4...
2   Ato_Aposentadoria  CONCEDER aposentadoria a CARLOS EDUARDO VIANA ...
3   Ato_Aposentadoria  CONCEDER aposentadoria a JULIANO GUEDES DE OLI...
4   Ato_Aposentadoria  CONCEDER APOSENTADORIA nos termos do artigo 3o...
..                ...                                                ...
75       Ato_Reversao  REVERTER a atividade nos termos do artigo 34, ...
76       Ato_Reversao  REVERTER a atividade nos termos do artigo 34, ...
77       Ato_Reversao  REVERTER a atividade nos termos do artigo 34, ...
78       Ato_Reversao  REVERTER a atividade nos termos do artigo 34, ...
79       Ato_Reversao  REVERTER a atividade nos termos do artigo 34, ...

[80 rows x 2 columns]

### Unificação dos datasets

In [16]:
d = {'aposentadoria': 'Ato_Aposentadoria',
    'nomeacao': 'Ato_Nomeacao_Comissionado',
    'exoneracao': 'Ato_Exoneracao_Comissionado',
    'substituicao': 'Ato_Substituicao',
    'cessao': 'Ato_Cessao',
    'abono_de_permanência': 'Ato_Abono_Permanencia',
    'reversao': 'Ato_Reversao',
    'Ato_Nomeacao_Efetivo': 'Ato_Nomeacao_Efetivo',
    'Ato_Exoneracao_Efetivo': 'Ato_Exoneracao_Efetivo'}

In [17]:
df2.tipo_ato = df2.tipo_ato.apply(lambda x: d[x])

In [18]:
df = pd.concat([df1, df2, df3]).reset_index(drop = True)
df

,tipo_ato,ato
0,Ato_Reversao,REVERTER o REGIME DE TEMPO INTEGRAL E DEDICACA...
1,Ato_Nomeacao_Comissionado,NOMEAR JOAO PAULO PATROCINA MARQUES para exerc...
2,Ato_Exoneracao_Comissionado,EXONERAR SEBASTIAO FRANCISCO DE QUEIROZ do Car...
3,Ato_Exoneracao_Comissionado,EXONERAR SEBASTIAO FRANCISCO DE QUEIROZ do Car...
4,Ato_Exoneracao_Comissionado,EXONERAR SEBASTIAO FRANCISCO DE QUEIROZ do Car...
...,...,...
2556,Ato_Reversao,"REVERTER a atividade nos termos do artigo 34, ..."
2557,Ato_Reversao,"REVERTER a atividade nos termos do artigo 34, ..."
2558,Ato_Reversao,"REVERTER a atividade nos termos do artigo 34, ..."
2559,Ato_Reversao,"REVERTER a atividade nos termos do artigo 34, ..."
2560,Ato_Reversao,"REVERTER a atividade nos termos do artigo 34, ..."

In [19]:
df['tipo_ato'].value_counts()

Ato_Nomeacao_Comissionado         795
Ato_Exoneracao_Comissionado       548
Ato_Tornado_Sem_Efeito_Exo_Nom    272
Ato_Retificacao_Comissionado      224
Ato_Substituicao                  176
Ato_Retificacao_Efetivo           174
Ato_Aposentadoria                 134
Ato_Exoneracao_Efetivo            122
Ato_Cessao                         39
Ato_Reversao                       34
Ato_Abono_Permanencia              15
Ato_Tornado_Sem_Efeito_Apo         15
Ato_Nomeacao_Efetivo               13
Name: tipo_ato, dtype: int64

In [20]:
for ato in df.loc[df.tipo_ato == 'Ato_Abono_Permanencia']['ato']:
    print(ato, end = '\n\n')

CONCEDER abono de permanencia ao servidor VALDIR MOREIRA DA SILVA, matricula
27.651-0, no cargo de Auditor Fiscal de Atividades Urbanas, Classe Especial, Padrao V,
do Quadro de Pessoal do Distrito Federal, de acordo com o artigo 3o da EC no 47, de 05 de
julho de 2005, com amparo na Decisao no 20/2012  TCDF, por ter completado os requisitos
para aposentadoria voluntaria e optado por permanecer em atividade, a contar de 2/8/2013.
Processo 090.001.673/2014.

CONCEDER abono de permanencia as servidoras: ANEMARY MARIA DE OLIVEIRA
DELGADO, Agente de Policia, matricula SIGRH no 57.102-4, matricula SIAPE no 1410950, con-
forme processo no 052.001.471/2014, no periodo de 15.05.2014 a 02.07.2014; ELIANE ARAUJO
DAMASCENO, Agente de Policia, matricula SIGRH no 38.749-5, matricula SIAPE no 1409608,
conforme processo no 052.001.441/2014, no periodo de 16.05.2014 a 11.06.2014; ROSEANE DE
OLIVEIRA MORAES, Agente Penitenciario, matricula SIGRH no 58.611-0, matricula SIAPE no
1412079, conforme processo no 052.001.437/2014, a partir de 16.05.2014; JUSSARA MARTINS
PERES LOPES, Agente de Policia, matricula SIGRH no 27.562-X, matricula SIAPE no 1408733,
conforme processo no 052.001.447/2014, a partir de 16.05.2014; IONE MARIA PEREIRA, Agen-
te de Policia, matricula SIGRH no 31.536-2, matricula SIAPE no 1408990, conforme processo
no 052.001.433/2014, a partir de 16.05.2014; VERA LUCIA PEREIRA DE ARAUJO, Agente
de Policia, matricula SIGRH no 47.593-9, matricula SIAPE no 1410641, conforme processo no
052.001.474/2014, a partir de 11.06.2014; MARIA DAS GRACAS SILVA, Escriva de Policia, ma-
tricula SIGRH no 57.119-9, matricula SIAPE no 1410958, conforme processo no 052.001.438/2014,
a partir de 16.05.2014; ELISABETE EMIDIO DA COSTA, Agente Penitenciario, matricula SIGRH
no 27.886-6, matricula SIAPE no 1408867, conforme processo no 052.001.436/2014, a partir de
16.05.2014; CARLA OLIVEIRA DA CRUZ, Agente de Policia, matricula SIGRH no 34.148-7,
matricula SIAPE no 0001949, conforme processo no 052.001.450/2014, no periodo de 16.05.2014
a 26.06.2014 e ROSENY FERREIRA DOS SANTOS, Escriva de Policia, matricula SIGRH no
47.100-3, matricula SIAPE no 1410368, conforme processo no 052.001.444/2014, a partir de
17.06.2014; todas com fundamento no  19, do artigo 40 da Constituicao Federal e na Decisao
no 2623/2010 do TCDF, por haver implementado tempo de contribuicao para aposentacao, nos
termos do artigo 1o, inciso II, alinea b da Lei Complementar no 51, de 20 de dezembro de 1985,
com redacao dada pela Lei Complementar no 144, de 15 de maio de 2014.

CONCEDER Abono de Permanencia, equivalente ao valor
da respectiva contribuicao previdenciaria, de acordo com o 5o, do artigo 2o, da Emenda
Constitucional no 41, de 19 de dezembro de 2003, c/c a Lei Complementar no 700, de 04
de outubro de 2004, c/c a Lei Complementar no 769, de 30 de junho de 2008 a MARI-
ZETE GONZAGA DOS SANTOS, matricula 23.959-3, a contar de 04 de abril de 2013.
Processo 098.002.450/2013.

CONCEDER Abono de Permanencia a JUSCELINO DE
ARAUJO, Perito Criminal, matricula SIGRH 27.120-9 e matricula SIAPE 1408618, a
partir de 17.11.2013, conforme processo 052.001.837/2013, com fundamento no  19,
do artigo 40, da Constituicao Federal e na Decisao no 2623/2010 do TCDF, por haver
implementado tempo de contribuicao para aposentacao, nos termos do artigo 1o, inciso I,
da Lei Complementar no 51/85.

CONCEDER
abono de permanencia equivalente ao valor da respectiva contribuicao previdenciaria ao
servidor GILBERTO COSTA DA SILVA, matricula 101.587-7, Tecnico em Assistencia
Social, Classe Especial, Padrao V, de acordo com o Art. 2o da Emenda Constitucional no
41/2003, combinado com o Art. 45 da Lei Complementar n 769/2008 e combinado com
o Art. 114 da Lei Complementar no 840/2011, a contar de 02 de abril de 2013, conforme
processo 0417-001944/2013.

CONCEDER
abono de permanencia equivalente ao valor da respectiva contribuicao previdenciaria ao
servidor RUBENS FRANCISCO FERREIRA, matricula 101.945-7, Tecnico em Assistencia
Social, Classe Especial, Padrao V, de acordo com o Art. 2o da Emenda Constitucional no
41/2003, combinado com o Art. 45 da Lei Complementar n 769/2008 e combinado com o
Art. 114 da Lei Complementar no 840/2011, a contar de 20 de outubro de 2012, conforme
processo 0417-001910/2013.

CONCEDER abono de permanencia ao servidor ANDRE FRANCISCO DOURADO, matri-
cula 100.434-4, no cargo de Auxiliar de Desenvolvimento e Fiscalizacao Agropecuaria, Classe
Especial, Padrao III, do Quadro de Pessoal do Distrito Federal, de acordo com o artigo 2,  5,
da EC n 41/ 2003, por ter completado os requisitos para aposentadoria voluntaria e optado por
permanecer em atividade, a contar de 3/5/2013. Processo 070.001.278/2013.

CONCEDER abono de permanencia ao servidor ANTONIO MARCOS AUGUSTO, matricula
100.397-6, no cargo de Tecnico de Desenvolvimento e Fiscalizacao Agropecuaria, Classe Es-
pecial, Padrao III, do Quadro de Pessoal do Distrito Federal, de acordo com o artigo 2,  5,
da EC n 41/ 2003, por ter completado os requisitos para aposentadoria voluntaria e optado por
permanecer em atividade, a contar de 2/7/2013. Processo 070.001.279/2013.

CONCEDER abono de permanencia ao servidor PAULO SEVERO FRAGA RIOS, matricula
101.094-8, no cargo de Tecnico de Desenvolvimento e Fiscalizacao Agropecuaria, Classe Es-
pecial, Padrao III, do Quadro de Pessoal do Distrito Federal, de acordo com o artigo 2,  5,
da EC n 41/ 2003, por ter completado os requisitos para aposentadoria voluntaria e optado por
permanecer em atividade, a contar de 10/7/2013. Processo 070.001.284/2013

CONCEDER Abono de Permanencia ao
servidor EDUARDO FERNANDES DA SILVA, matricula 46.215-2, Auditor-Fiscal da
Receita do Distrito Federal, Classe Especial, Padrao V, do Quadro de Pessoal do Distrito
Federal, nos termos do  19, do artigo 40, da Constituicao Federal, com a redacao dada pela
Emenda Constitucional no 41, de 19 de dezembro de 2003, a contar de 06 de fevereiro de
2013. Processo 040.002.286/2012.

CONCEDER Abono de Permanencia a FRANCISCO EXPEDITO RODRIGUES DE MELO,
Escrivao de Policia, matricula SIGRH no 35.385-X e matricula SIAPE no 1410278, a partir de
29.06.2013, conforme processo 052.001.365/2013, com fundamento no  19, do artigo 40 da
Constituicao Federal e na Decisao no 2623/2010 do TCDF, por haver implementado tempo de
contribuicao para aposentacao, nos termos do artigo 1o, inciso I, da Lei Complementar no 51/85.

CONCEDER abono de permanencia aos servidores: AMADEU BARROS LIMA,
Tecnico de Apoio as Atividades Policiais Civis, aposentado, matricula SIGRH no 25.365-0, o
periodo compreendido entre 05.04.2008 a 07.04.2013, conforme processo no 052.000.847/2013 e
ELY WANDERLEY DE GONCALVES PRADO, Tecnico de Apoio as Atividades Policiais Civis,
matricula SIGRH no 25.173-9 e matricula SIAPE no 1416187, a partir de 21.04.2013, conforme
processo no 052.000.940/2013, ambos com fundamento no artigo 2 o,  5o da Emenda Consti-
tucional no 41 de 19.12.2003, c/c o artigo 45,  1o da Lei Complementar no 769, de 30.06.2008.

CONCEDER abono de permanencia aos servidores: AMADEU BARROS LIMA,
Tecnico de Apoio as Atividades Policiais Civis, aposentado, matricula SIGRH no 25.365-0, o
periodo compreendido entre 05.04.2008 a 07.04.2013, conforme processo no 052.000.847/2013 e
ELY WANDERLEY DE GONCALVES PRADO, Tecnico de Apoio as Atividades Policiais Civis,
matricula SIGRH no 25.173-9 e matricula SIAPE no 1416187, a partir de 21.04.2013, conforme
processo no 052.000.940/2013, ambos com fundamento no artigo 2 o,  5o da Emenda Consti-
tucional no 41 de 19.12.2003, c/c o artigo 45,  1o da Lei Complementar no 769, de 30.06.2008.

CONCEDER abono de permanencia a ELSON AUGUSTO DE MENDONCA, Agente
de Policia, matricula SIGRH no 27.863-7 e matricula SIAPE no 1408853, a partir de 02.09.2013,
conforme processo no 052.001.538/2013 com fundamento no  19, do artigo 40 da Constituicao
Federal e na Decisao no 2623/2010 do TCDF, por haver implementado tempo de contribuicao
para aposentacao, nos termos do artigo 1o, inciso I, da Lei Complementar no 51/85.

CONCEDER ABONO DE PERMANÊNCIA, equivalente ao valor
da sua contribuição previdenciária, nos termos do art. 114 da Lei Complementar nº 840,
de 23 de dezembro de 2011, e com base na Decisão nº 20/2012 do Tribunal de Contas do
Distrito Federal, e no art. 3º da Emenda Constitucional nº 47/2005, à servidora
ALDANICE VIEIRA DE MELO, Inspetor Fiscal, matrícula 43.368-3, por haver
completado os requisitos para aposentadoria e optado por permanecer em atividade,
ressaltando que não foram utilizados períodos de licença prêmio por assiduidade na
apuração do tempo de serviço para a concessão desse benefício, conforme Processo SEIGDF nº 04017.00010289/2020-81, com vigência a contar de 13 de junho de 2020.

### Retira caracteres não-alfanuméricos ("(", ",", ".", "\n", etc)

In [21]:
df.ato = df.ato.str.replace('\W', ' ')
df

,tipo_ato,ato
0,Ato_Reversao,REVERTER o REGIME DE TEMPO INTEGRAL E DEDICACA...
1,Ato_Nomeacao_Comissionado,NOMEAR JOAO PAULO PATROCINA MARQUES para exerc...
2,Ato_Exoneracao_Comissionado,EXONERAR SEBASTIAO FRANCISCO DE QUEIROZ do Car...
3,Ato_Exoneracao_Comissionado,EXONERAR SEBASTIAO FRANCISCO DE QUEIROZ do Car...
4,Ato_Exoneracao_Comissionado,EXONERAR SEBASTIAO FRANCISCO DE QUEIROZ do Car...
...,...,...
2556,Ato_Reversao,REVERTER a atividade nos termos do artigo 34 ...
2557,Ato_Reversao,REVERTER a atividade nos termos do artigo 34 ...
2558,Ato_Reversao,REVERTER a atividade nos termos do artigo 34 ...
2559,Ato_Reversao,REVERTER a atividade nos termos do artigo 34 ...
2560,Ato_Reversao,REVERTER a atividade nos termos do artigo 34 ...

### Remoção de stopwords

In [22]:
stopwords = nltk.corpus.stopwords.words('portuguese')

In [23]:
df['ato'] = df['ato'].apply(lambda x: ' '.join([item for item in x.split() if item not in stopwords]))
df

,tipo_ato,ato
0,Ato_Reversao,REVERTER REGIME DE TEMPO INTEGRAL E DEDICACAO ...
1,Ato_Nomeacao_Comissionado,NOMEAR JOAO PAULO PATROCINA MARQUES exercer Ca...
2,Ato_Exoneracao_Comissionado,EXONERAR SEBASTIAO FRANCISCO DE QUEIROZ Cargo ...
3,Ato_Exoneracao_Comissionado,EXONERAR SEBASTIAO FRANCISCO DE QUEIROZ Cargo ...
4,Ato_Exoneracao_Comissionado,EXONERAR SEBASTIAO FRANCISCO DE QUEIROZ Cargo ...
...,...,...
2556,Ato_Reversao,REVERTER atividade termos artigo 34 Inciso I I...
2557,Ato_Reversao,REVERTER atividade termos artigo 34 Inciso I I...
2558,Ato_Reversao,REVERTER atividade termos artigo 34 Inciso I I...
2559,Ato_Reversao,REVERTER atividade termos artigo 34 Inciso I I...
2560,Ato_Reversao,REVERTER atividade termos artigo 34 Inciso I I...

### Stemming

In [24]:
stemmer = nltk.stem.RSLPStemmer()

In [25]:
df['ato'] = df['ato'].apply(lambda x: ' '.join([stemmer.stem(item) for item in x.split()]))
df

,tipo_ato,ato
0,Ato_Reversao,revert regim de temp integr e dedicaca exclus ...
1,Ato_Nomeacao_Comissionado,nome joa paul patrocin marqu exerc carg comiss...
2,Ato_Exoneracao_Comissionado,exoner sebastia francisc de queiroz carg comis...
3,Ato_Exoneracao_Comissionado,exoner sebastia francisc de queiroz carg comis...
4,Ato_Exoneracao_Comissionado,exoner sebastia francisc de queiroz carg comis...
...,...,...
2556,Ato_Reversao,revert ativ term artig 34 incis i ii lei compl...
2557,Ato_Reversao,revert ativ term artig 34 incis i ii lei compl...
2558,Ato_Reversao,revert ativ term artig 34 incis i ii lei compl...
2559,Ato_Reversao,revert ativ term artig 34 incis i ii lei compl...
2560,Ato_Reversao,revert ativ term artig 34 incis i ii lei compl...

### Aplicação do tfidf

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(stop_words=stopwords, max_df = 0.9, min_df=2)

In [27]:
X = vectorizer.fit_transform(df['ato'])
X

<2561x2900 sparse matrix of type '<class 'numpy.float64'>'
	with 87328 stored elements in Compressed Sparse Row format>

In [28]:
df.loc[df.ato.str.contains("abon") & df.ato.str.contains("permanenc")]

,tipo_ato,ato
226,Ato_Abono_Permanencia,conced abon permanenc serv vald mor da silv ma...
311,Ato_Retificacao_Comissionado,na port 13 06 2014 secret est educaca distrit ...
312,Ato_Retificacao_Comissionado,na port 13 06 2014 secret est educaca distrit ...
508,Ato_Abono_Permanencia,conced abon permanenc serv anemary mar de oliv...
510,Ato_Retificacao_Efetivo,na ord serv 32 17 julh 2014 public dodf 146 18...
535,Ato_Abono_Permanencia,conced abon permanenc equival val respec contr...
1316,Ato_Abono_Permanencia,conced abon permanenc juscelin de arauj perit ...
1319,Ato_Abono_Permanencia,conced abon permanenc equival val respec contr...
1320,Ato_Abono_Permanencia,conced abon permanenc equival val respec contr...
1642,Ato_Abono_Permanencia,conced abon permanenc serv andr francisc dour ...
1643,Ato_Abono_Permanencia,conced abon permanenc serv antoni marc august ...
1644,Ato_Abono_Permanencia,conced abon permanenc serv paul sever frag rio...
1645,Ato_Abono_Permanencia,conced abon permanenc serv eduard fernand da s...
1646,Ato_Abono_Permanencia,conced abon permanenc francisc expedit rodrig ...
1819,Ato_Abono_Permanencia,conced abon permanenc serv amad barr lim tecn ...
1820,Ato_Abono_Permanencia,conced abon permanenc serv amad barr lim tecn ...
2046,Ato_Abono_Permanencia,conced abon permanenc elson august de mendonc ...

# Classificação

In [31]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

from sklearn.svm import SVC # SVM
from sklearn.ensemble import RandomForestClassifier # Random Forest
from sklearn.neural_network import MLPClassifier # MLP
from sklearn.linear_model import LogisticRegression # Logistic Regression
from sklearn.naive_bayes import GaussianNB # Naive Bayes (Gaussian)
from sklearn.naive_bayes import ComplementNB # Naive Bayes (Complement)
from sklearn.tree import DecisionTreeClassifier # Decision Tree
from sklearn.linear_model import SGDClassifier # Stochastic Gradient Descent

In [32]:
y = np.array(df['tipo_ato'])

In [33]:
from sklearn.model_selection import StratifiedKFold
kf = StratifiedKFold(n_splits = 5, random_state = 87, shuffle = True)

### Função de Random Search

In [43]:
def RSearchCV(clf, X, y, kfold = 5, iteracoes = 25, threads = -1, verbose = 0):

    classificadores = {
                       "SVM": (SVC(), [{'kernel': ['rbf'], 'gamma': ['auto', 'scale', 2, 1, 0.3, 0.1, 1e-2, 1e-3, 1e-4],
                                 'C': [0.5, 1, 2, 5, 30, 100, 300, 1000]},
                                 {'kernel': ['linear'], 'C': [0.5, 1, 2, 5, 30, 100, 300, 1000]}]),
                       
                       "RandomForestClassifier": (RandomForestClassifier(), {'max_features': ['sqrt', 'log2', 0.03, 0.1, 0.2, 0.4, 0.7], 
                                                   'n_estimators': [10, 25, 50, 100, 200, 300, 500, 1000, 1500],
                                                    'n_jobs': [2], 'random_state': [87]}),
                       
                       "MLP": (MLPClassifier(), {'solver': ['sgd', 'adam'], 
                                           'hidden_layer_sizes': [5, 10, 15, 20, (10, 10), (15, 10), (15, 15), (10, 10, 10)],
                                            'max_iter': [800, 1100, 1400, 1700], 'random_state': [87]}),
                       
                       "LogisticRegression": (LogisticRegression(), {'penalty': ['l1', 'l2', 'elasticnet'], 'C': [0.4, 0.8, 1.2, 1.6], 
                                               'solver': ['newton-cg', 'liblinear', 'saga']}),
                       
                       "GaussianNB": (GaussianNB(), {'var_smoothing': [1e-5, 1e-6, 1e-7, 1e-8, 1e-9, 1e-10]}),

                       "ComplementNB": (ComplementNB(), {'alpha': [0, 0.4, 0.8, 1.2, 1.6], 'norm': [True, False]}),

                       "DecisionTreeClassifier": (DecisionTreeClassifier(), {'criterion': ['gini', 'entropy'], 'random_state': [87], 
                                                    'class_weight': [None, 'balanced'], 'min_samples_split': [2, 10, 50, 100], 
                                                    'min_samples_leaf': [1, 5, 25]}),
                       
                       "SGDClassifier": (SGDClassifier(), {'loss': ['modified_huber', 'log'], 
                                          'penalty': ['l2', 'l1', 'elasticnet'], 'alpha': [0.00005, 0.0001, 0.0002], 'random_state': [87]})
    
    }
    
    score = 'f1_macro'
    classificador = classificadores[clf][0]
    parametros = classificadores[clf][1]
    
    clf = RandomizedSearchCV(classificador, param_distributions = parametros, n_iter = iteracoes, cv = kfold, random_state = 87, scoring = score, verbose = verbose, n_jobs = threads)
    clf.fit(X, y)
        
    return clf.best_estimator_

### Teste com o KFold

In [35]:
index = 1
clfs_rf = []
for train, test in kf.split(X, y):
    print("Teste #%d" %index)
    X_train = X[train]
    X_test = X[test]
    y_train = y[train]
    y_test = y[test]
    
    clf = RSearchCV("RandomForestClassifier", X_train, y_train)
    clf.fit(X_train, y_train)
    clfs_rf.append(clf)
    
    y_true, y_pred = y_test, clf.predict(X_test)
    print(classification_report(y_true, y_pred), end = '\n\n')
    index += 1 # started at 00h37

Teste #1
                                precision    recall  f1-score   support

         Ato_Abono_Permanencia       1.00      0.67      0.80         3
             Ato_Aposentadoria       0.96      1.00      0.98        27
                    Ato_Cessao       1.00      1.00      1.00         8
   Ato_Exoneracao_Comissionado       0.99      1.00      1.00       110
        Ato_Exoneracao_Efetivo       1.00      1.00      1.00        24
     Ato_Nomeacao_Comissionado       1.00      0.99      1.00       159
          Ato_Nomeacao_Efetivo       1.00      1.00      1.00         3
  Ato_Retificacao_Comissionado       0.96      0.98      0.97        45
       Ato_Retificacao_Efetivo       0.97      0.94      0.96        35
                  Ato_Reversao       1.00      1.00      1.00         7
              Ato_Substituicao       1.00      1.00      1.00        35
    Ato_Tornado_Sem_Efeito_Apo       1.00      1.00      1.00         3
Ato_Tornado_Sem_Efeito_Exo_Nom       1.00      1.00      1.00        54

                      accuracy                           0.99       513
                     macro avg       0.99      0.97      0.98       513
                  weighted avg       0.99      0.99      0.99       513


Teste #2
                                precision    recall  f1-score   support

         Ato_Abono_Permanencia       1.00      1.00      1.00         3
             Ato_Aposentadoria       1.00      1.00      1.00        26
                    Ato_Cessao       1.00      1.00      1.00         8
   Ato_Exoneracao_Comissionado       0.98      0.98      0.98       110
        Ato_Exoneracao_Efetivo       1.00      0.92      0.96        25
     Ato_Nomeacao_Comissionado       0.98      1.00      0.99       159
          Ato_Nomeacao_Efetivo       1.00      1.00      1.00         2
  Ato_Retificacao_Comissionado       0.98      0.96      0.97        45
       Ato_Retificacao_Efetivo       0.94      0.94      0.94        35
                  Ato_Reversao       1.00      0.86      0.92         7
              Ato_Substituicao       1.00      1.00      1.00        35
    Ato_Tornado_Sem_Efeito_Apo       1.00      1.00      1.00         3
Ato_Tornado_Sem_Efeito_Exo_Nom       0.98      1.00      0.99        54

                      accuracy                           0.98       512
                     macro avg       0.99      0.97      0.98       512
                  weighted avg       0.98      0.98      0.98       512


Teste #3
                                precision    recall  f1-score   support

         Ato_Abono_Permanencia       1.00      1.00      1.00         3
             Ato_Aposentadoria       1.00      1.00      1.00        27
                    Ato_Cessao       1.00      1.00      1.00         8
   Ato_Exoneracao_Comissionado       0.98      1.00      0.99       109
        Ato_Exoneracao_Efetivo       1.00      0.92      0.96        25
     Ato_Nomeacao_Comissionado       1.00      1.00      1.00       159
          Ato_Nomeacao_Efetivo       1.00      1.00      1.00         2
  Ato_Retificacao_Comissionado       0.98      0.95      0.97        44
       Ato_Retificacao_Efetivo       0.94      0.97      0.96        35
                  Ato_Reversao       1.00      0.86      0.92         7
              Ato_Substituicao       0.97      1.00      0.99        35
    Ato_Tornado_Sem_Efeito_Apo       1.00      1.00      1.00         3
Ato_Tornado_Sem_Efeito_Exo_Nom       1.00      1.00      1.00        55

                      accuracy                           0.99       512
                     macro avg       0.99      0.98      0.98       512
                  weighted avg       0.99      0.99      0.99       512


Teste #4
                                precision    recall  f1-score   support

         Ato_Abono_Permanencia       0.67      0.67      0.67         3
             Ato_Aposentadoria       0.90      0.96      0.93        27
                    Ato_Cessao       1.00      0.75      0.86         8
   Ato_Exoneracao_Comissionado       0.99      0.97      0.98       109
        Ato_Exoneracao_Efetivo       1.00      0.96      0.98        24
     Ato_Nomeacao_Comissionado       0.98      1.00      0.99       159
          Ato_Nomeacao_Efetivo       1.00      0.67      0.80         3
  Ato_Retificacao_Comissionado       1.00      0.98      0.99        45
       Ato_Retificacao_Efetivo       0.97      0.97      0.97        34
                  Ato_Reversao       0.60      0.86      0.71         7
              Ato_Substituicao       0.97      0.91      0.94        35
    Ato_Tornado_Sem_Efeito_Apo       1.00      1.00      1.00         3
Ato_Tornado_Sem_Efeito_Exo_Nom       1.00      1.00      1.00        55

                      accuracy                           0.97       512
                     macro avg       0.93      0.90      0.91       512
                  weighted avg       0.97      0.97      0.97       512


Teste #5
                                precision    recall  f1-score   support

         Ato_Abono_Permanencia       1.00      0.67      0.80         3
             Ato_Aposentadoria       1.00      0.96      0.98        27
                    Ato_Cessao       1.00      1.00      1.00         7
   Ato_Exoneracao_Comissionado       0.99      1.00      1.00       110
        Ato_Exoneracao_Efetivo       1.00      0.96      0.98        24
     Ato_Nomeacao_Comissionado       1.00      1.00      1.00       159
          Ato_Nomeacao_Efetivo       1.00      1.00      1.00         3
  Ato_Retificacao_Comissionado       0.98      0.96      0.97        45
       Ato_Retificacao_Efetivo       0.94      0.97      0.96        35
                  Ato_Reversao       1.00      1.00      1.00         6
              Ato_Substituicao       0.95      1.00      0.97        36
    Ato_Tornado_Sem_Efeito_Apo       1.00      1.00      1.00         3
Ato_Tornado_Sem_Efeito_Exo_Nom       1.00      1.00      1.00        54

                      accuracy                           0.99       512
                     macro avg       0.99      0.96      0.97       512
                  weighted avg       0.99      0.99      0.99       512

In [36]:
index = 1
clfs_dt = []
for train, test in kf.split(X, y):
    print("Teste #%d" %index)
    X_train = X[train]
    X_test = X[test]
    y_train = y[train]
    y_test = y[test]
    
    clf = RSearchCV("DecisionTreeClassifier", X_train, y_train)
    clf.fit(X_train, y_train)
    clfs_dt.append(clf)
    
    y_true, y_pred = y_test, clf.predict(X_test)
    print(classification_report(y_true, y_pred), end = '\n\n')
    index += 1

Teste #1
                                precision    recall  f1-score   support

         Ato_Abono_Permanencia       0.75      1.00      0.86         3
             Ato_Aposentadoria       1.00      0.96      0.98        27
                    Ato_Cessao       1.00      1.00      1.00         8
   Ato_Exoneracao_Comissionado       0.96      1.00      0.98       110
        Ato_Exoneracao_Efetivo       1.00      1.00      1.00        24
     Ato_Nomeacao_Comissionado       1.00      0.97      0.99       159
          Ato_Nomeacao_Efetivo       1.00      1.00      1.00         3
  Ato_Retificacao_Comissionado       0.94      0.98      0.96        45
       Ato_Retificacao_Efetivo       0.94      0.91      0.93        35
                  Ato_Reversao       1.00      1.00      1.00         7
              Ato_Substituicao       1.00      0.97      0.99        35
    Ato_Tornado_Sem_Efeito_Apo       0.75      1.00      0.86         3
Ato_Tornado_Sem_Efeito_Exo_Nom       1.00      0.98      0.99        54

                      accuracy                           0.98       513
                     macro avg       0.95      0.98      0.96       513
                  weighted avg       0.98      0.98      0.98       513


Teste #2
                                precision    recall  f1-score   support

         Ato_Abono_Permanencia       1.00      1.00      1.00         3
             Ato_Aposentadoria       1.00      1.00      1.00        26
                    Ato_Cessao       1.00      1.00      1.00         8
   Ato_Exoneracao_Comissionado       0.99      0.96      0.98       110
        Ato_Exoneracao_Efetivo       0.92      0.96      0.94        25
     Ato_Nomeacao_Comissionado       0.99      1.00      0.99       159
          Ato_Nomeacao_Efetivo       1.00      0.50      0.67         2
  Ato_Retificacao_Comissionado       0.98      1.00      0.99        45
       Ato_Retificacao_Efetivo       1.00      0.94      0.97        35
                  Ato_Reversao       1.00      0.86      0.92         7
              Ato_Substituicao       0.95      1.00      0.97        35
    Ato_Tornado_Sem_Efeito_Apo       1.00      1.00      1.00         3
Ato_Tornado_Sem_Efeito_Exo_Nom       0.98      1.00      0.99        54

                      accuracy                           0.98       512
                     macro avg       0.99      0.94      0.96       512
                  weighted avg       0.98      0.98      0.98       512


Teste #3
                                precision    recall  f1-score   support

         Ato_Abono_Permanencia       1.00      1.00      1.00         3
             Ato_Aposentadoria       1.00      1.00      1.00        27
                    Ato_Cessao       1.00      1.00      1.00         8
   Ato_Exoneracao_Comissionado       0.97      1.00      0.99       109
        Ato_Exoneracao_Efetivo       1.00      0.92      0.96        25
     Ato_Nomeacao_Comissionado       1.00      0.99      1.00       159
          Ato_Nomeacao_Efetivo       1.00      1.00      1.00         2
  Ato_Retificacao_Comissionado       0.95      0.95      0.95        44
       Ato_Retificacao_Efetivo       0.94      0.94      0.94        35
                  Ato_Reversao       1.00      0.86      0.92         7
              Ato_Substituicao       0.97      1.00      0.99        35
    Ato_Tornado_Sem_Efeito_Apo       1.00      1.00      1.00         3
Ato_Tornado_Sem_Efeito_Exo_Nom       1.00      1.00      1.00        55

                      accuracy                           0.98       512
                     macro avg       0.99      0.97      0.98       512
                  weighted avg       0.98      0.98      0.98       512


Teste #4
                                precision    recall  f1-score   support

         Ato_Abono_Permanencia       1.00      0.67      0.80         3
             Ato_Aposentadoria       0.96      0.96      0.96        27
                    Ato_Cessao       1.00      0.88      0.93         8
   Ato_Exoneracao_Comissionado       1.00      0.90      0.95       109
        Ato_Exoneracao_Efetivo       0.74      0.96      0.84        24
     Ato_Nomeacao_Comissionado       0.98      1.00      0.99       159
          Ato_Nomeacao_Efetivo       1.00      1.00      1.00         3
  Ato_Retificacao_Comissionado       0.91      0.96      0.93        45
       Ato_Retificacao_Efetivo       0.94      0.85      0.89        34
                  Ato_Reversao       0.47      1.00      0.64         7
              Ato_Substituicao       1.00      0.89      0.94        35
    Ato_Tornado_Sem_Efeito_Apo       1.00      1.00      1.00         3
Ato_Tornado_Sem_Efeito_Exo_Nom       1.00      1.00      1.00        55

                      accuracy                           0.95       512
                     macro avg       0.92      0.93      0.91       512
                  weighted avg       0.96      0.95      0.95       512


Teste #5
                                precision    recall  f1-score   support

         Ato_Abono_Permanencia       1.00      0.67      0.80         3
             Ato_Aposentadoria       0.96      0.96      0.96        27
                    Ato_Cessao       1.00      0.86      0.92         7
   Ato_Exoneracao_Comissionado       0.98      1.00      0.99       110
        Ato_Exoneracao_Efetivo       0.96      0.92      0.94        24
     Ato_Nomeacao_Comissionado       1.00      1.00      1.00       159
          Ato_Nomeacao_Efetivo       1.00      1.00      1.00         3
  Ato_Retificacao_Comissionado       0.96      0.98      0.97        45
       Ato_Retificacao_Efetivo       0.97      0.94      0.96        35
                  Ato_Reversao       1.00      0.83      0.91         6
              Ato_Substituicao       0.95      1.00      0.97        36
    Ato_Tornado_Sem_Efeito_Apo       1.00      1.00      1.00         3
Ato_Tornado_Sem_Efeito_Exo_Nom       1.00      1.00      1.00        54

                      accuracy                           0.98       512
                     macro avg       0.98      0.94      0.96       512
                  weighted avg       0.98      0.98      0.98       512

In [44]:
index = 1
clfs_sgd = []
for train, test in kf.split(X, y):
    print("Teste #%d" %index)
    X_train = X[train]
    X_test = X[test]
    y_train = y[train]
    y_test = y[test]
    
    clf = RSearchCV("SGDClassifier", X_train, y_train)
    clf.fit(X_train, y_train)
    clfs_sgd.append(clf)
    
    y_true, y_pred = y_test, clf.predict(X_test)
    print(classification_report(y_true, y_pred), end = '\n\n')
    index += 1

Teste #1

C:\Users\felip\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:278: UserWarning: The total space of parameters 18 is smaller than n_iter=25. Running 18 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

                                precision    recall  f1-score   support

         Ato_Abono_Permanencia       0.75      1.00      0.86         3
             Ato_Aposentadoria       1.00      1.00      1.00        27
                    Ato_Cessao       1.00      1.00      1.00         8
   Ato_Exoneracao_Comissionado       0.99      1.00      1.00       110
        Ato_Exoneracao_Efetivo       1.00      1.00      1.00        24
     Ato_Nomeacao_Comissionado       1.00      0.99      1.00       159
          Ato_Nomeacao_Efetivo       1.00      1.00      1.00         3
  Ato_Retificacao_Comissionado       0.94      1.00      0.97        45
       Ato_Retificacao_Efetivo       1.00      0.86      0.92        35
                  Ato_Reversao       1.00      1.00      1.00         7
              Ato_Substituicao       0.97      1.00      0.99        35
    Ato_Tornado_Sem_Efeito_Apo       1.00      1.00      1.00         3
Ato_Tornado_Sem_Efeito_Exo_Nom       1.00      1.00      1.00        54

                      accuracy                           0.99       513
                     macro avg       0.97      0.99      0.98       513
                  weighted avg       0.99      0.99      0.99       513


Teste #2

C:\Users\felip\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:278: UserWarning: The total space of parameters 18 is smaller than n_iter=25. Running 18 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

                                precision    recall  f1-score   support

         Ato_Abono_Permanencia       1.00      1.00      1.00         3
             Ato_Aposentadoria       1.00      1.00      1.00        26
                    Ato_Cessao       1.00      1.00      1.00         8
   Ato_Exoneracao_Comissionado       0.98      0.98      0.98       110
        Ato_Exoneracao_Efetivo       1.00      0.96      0.98        25
     Ato_Nomeacao_Comissionado       0.98      1.00      0.99       159
          Ato_Nomeacao_Efetivo       1.00      1.00      1.00         2
  Ato_Retificacao_Comissionado       0.98      0.91      0.94        45
       Ato_Retificacao_Efetivo       0.89      0.91      0.90        35
                  Ato_Reversao       1.00      0.86      0.92         7
              Ato_Substituicao       1.00      1.00      1.00        35
    Ato_Tornado_Sem_Efeito_Apo       1.00      1.00      1.00         3
Ato_Tornado_Sem_Efeito_Exo_Nom       0.98      1.00      0.99        54

                      accuracy                           0.98       512
                     macro avg       0.99      0.97      0.98       512
                  weighted avg       0.98      0.98      0.98       512


Teste #3

C:\Users\felip\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:278: UserWarning: The total space of parameters 18 is smaller than n_iter=25. Running 18 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

                                precision    recall  f1-score   support

         Ato_Abono_Permanencia       1.00      1.00      1.00         3
             Ato_Aposentadoria       1.00      1.00      1.00        27
                    Ato_Cessao       1.00      1.00      1.00         8
   Ato_Exoneracao_Comissionado       0.99      1.00      1.00       109
        Ato_Exoneracao_Efetivo       1.00      1.00      1.00        25
     Ato_Nomeacao_Comissionado       0.99      0.99      0.99       159
          Ato_Nomeacao_Efetivo       1.00      1.00      1.00         2
  Ato_Retificacao_Comissionado       0.98      0.98      0.98        44
       Ato_Retificacao_Efetivo       0.97      0.97      0.97        35
                  Ato_Reversao       1.00      0.86      0.92         7
              Ato_Substituicao       1.00      1.00      1.00        35
    Ato_Tornado_Sem_Efeito_Apo       1.00      1.00      1.00         3
Ato_Tornado_Sem_Efeito_Exo_Nom       1.00      1.00      1.00        55

                      accuracy                           0.99       512
                     macro avg       0.99      0.98      0.99       512
                  weighted avg       0.99      0.99      0.99       512


Teste #4

C:\Users\felip\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:278: UserWarning: The total space of parameters 18 is smaller than n_iter=25. Running 18 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

                                precision    recall  f1-score   support

         Ato_Abono_Permanencia       1.00      1.00      1.00         3
             Ato_Aposentadoria       1.00      1.00      1.00        27
                    Ato_Cessao       1.00      0.88      0.93         8
   Ato_Exoneracao_Comissionado       0.98      0.97      0.98       109
        Ato_Exoneracao_Efetivo       1.00      0.96      0.98        24
     Ato_Nomeacao_Comissionado       0.97      1.00      0.98       159
          Ato_Nomeacao_Efetivo       1.00      1.00      1.00         3
  Ato_Retificacao_Comissionado       0.96      0.98      0.97        45
       Ato_Retificacao_Efetivo       0.97      0.94      0.96        34
                  Ato_Reversao       1.00      1.00      1.00         7
              Ato_Substituicao       1.00      0.94      0.97        35
    Ato_Tornado_Sem_Efeito_Apo       1.00      1.00      1.00         3
Ato_Tornado_Sem_Efeito_Exo_Nom       1.00      1.00      1.00        55

                      accuracy                           0.98       512
                     macro avg       0.99      0.97      0.98       512
                  weighted avg       0.98      0.98      0.98       512


Teste #5

C:\Users\felip\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:278: UserWarning: The total space of parameters 18 is smaller than n_iter=25. Running 18 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

                                precision    recall  f1-score   support

         Ato_Abono_Permanencia       1.00      1.00      1.00         3
             Ato_Aposentadoria       1.00      0.96      0.98        27
                    Ato_Cessao       1.00      1.00      1.00         7
   Ato_Exoneracao_Comissionado       0.98      1.00      0.99       110
        Ato_Exoneracao_Efetivo       1.00      0.96      0.98        24
     Ato_Nomeacao_Comissionado       0.99      1.00      1.00       159
          Ato_Nomeacao_Efetivo       1.00      1.00      1.00         3
  Ato_Retificacao_Comissionado       0.98      0.91      0.94        45
       Ato_Retificacao_Efetivo       0.92      0.94      0.93        35
                  Ato_Reversao       1.00      1.00      1.00         6
              Ato_Substituicao       0.97      1.00      0.99        36
    Ato_Tornado_Sem_Efeito_Apo       1.00      1.00      1.00         3
Ato_Tornado_Sem_Efeito_Exo_Nom       1.00      1.00      1.00        54

                      accuracy                           0.98       512
                     macro avg       0.99      0.98      0.99       512
                  weighted avg       0.98      0.98      0.98       512

RandomForest:
accuracy / macro avg
0.99 / 0.98
0.98 / 0.98
0.99 / 0.98
0.97 / 0.91
0.99 / 0.97 <--

Acurácia média: (0.99+0.98+0.99+0.97+0.99)/5 = 0.984
Acurácia Macro média: (0.98+0.98+0.98+0.91+0.97)/5 = 0.964

DecisionTree:
accuracy / macro avg
0.98 / 0.96 <--
0.98 / 0.96
0.98 / 0.98
0.95 / 0.91
0.98 / 0.96

Acurácia média: (0.98+0.98+0.98+0.95+0.98)/5 = 0.974
Acurácia Macro média: (0.96+0.96+0.98+0.91+0.96)/5 = 0.954

SGD:
accuracy / macro avg
0.99 / 0.98
0.98 / 0.98
0.99 / 0.99
0.98 / 0.98
0.98 / 0.99 <--

Acurácia média: (0.99+0.98+0.99+0.98+0.98)/5 = 0.984
Acurácia Macro média: (0.98+0.98+0.99+0.98+0.99)/5 = 0.984

In [38]:
import pickle

In [45]:
file = open('classificadores_treinados_com_2020', 'wb')
pickle.dump(clfs_rf[4], file)
pickle.dump(clfs_dt[0], file)
pickle.dump(clfs_sgd[4], file)
pickle.dump(vectorizer, file)
file.close()